<<<<<<< HEAD
CREATE TABLE PRODUIT(
   NUMPDT INT,
   libPdt VARCHAR(20) NOT NULL,
   stckPdt INT NOT NULL,
   PRIMARY KEY(NUMPDT),
   UNIQUE(libPdt)
)ENGINE=InnoDB;

CREATE TABLE CLIENT(
   NUMCLI INT,
   nomCli VARCHAR(30) NOT NULL,
   villeCli VARCHAR(50) NOT NULL,
   precisionCli VARCHAR(30) NOT NULL,
   PRIMARY KEY(NUMCLI),
   UNIQUE(nomCli,villeCli)
)ENGINE=InnoDB;

CREATE TABLE SORTIE(
   NUMSORT INT,
   dateSort DATETIME NOT NULL,
   NUMCLI INT NOT NULL,
   PRIMARY KEY(NUMSORT),
   FOREIGN KEY(NUMCLI) REFERENCES CLIENT(NUMCLI)
)ENGINE=InnoDB;

CREATE TABLE SAUNIER(
   NUMSAU INT,
   nomSau VARCHAR(30) NOT NULL,
   prenomSau VARCHAR(30) NOT NULL,
   villeSau VARCHAR(50) NOT NULL,
   PRIMARY KEY(NUMSAU)
)ENGINE=InnoDB;

CREATE TABLE Annee(
   numAnnee INT,
   PRIMARY KEY(numAnnee)
)ENGINE=InnoDB;

CREATE TABLE ENTREE(
   NUMENT INT,
   dateEnt DATETIME NOT NULL,
   qteEnt__t_ INT NOT NULL CHECK (qteEnt__t_ >0),
   NUMSAU INT NOT NULL,
   NUMPDT INT NOT NULL,
   PRIMARY KEY(NUMENT),
   FOREIGN KEY(NUMSAU) REFERENCES SAUNIER(NUMSAU),
   FOREIGN KEY(NUMPDT) REFERENCES PRODUIT(NUMPDT)
)ENGINE=InnoDB;

CREATE TABLE CONCERNER(
   NUMPDT INT,
   NUMSORT INT,
   qteSort_t_ INT NOT NULL,
   PRIMARY KEY(NUMPDT, NUMSORT),
   FOREIGN KEY(NUMPDT) REFERENCES PRODUIT(NUMPDT),
   FOREIGN KEY(NUMSORT) REFERENCES SORTIE(NUMSORT)
)ENGINE=InnoDB;

CREATE TABLE PRIX(
   NUMPDT INT,
   numAnnee INT,
   prixAchat INT,
   prixVente INT,
   PRIMARY KEY(NUMPDT, numAnnee),
   FOREIGN KEY(NUMPDT) REFERENCES PRODUIT(NUMPDT),
   FOREIGN KEY(numAnnee) REFERENCES Annee(numAnnee)
)ENGINE=InnoDB;
=======
CREATE TABLE PRODUIT(
   NUMPDT INT,
   libPdt VARCHAR(20) NOT NULL,
   stckPdt INT NOT NULL,
   PRIMARY KEY(NUMPDT),
   UNIQUE(libPdt)
)ENGINE=InnoDB;

CREATE TABLE CLIENT(
   NUMCLI INT,
   nomCli VARCHAR(30) NOT NULL,
   villeCli VARCHAR(50) NOT NULL,
   precisionCli VARCHAR(30) NOT NULL,
   PRIMARY KEY(NUMCLI),
   UNIQUE(nomCli,villeCli)
)ENGINE=InnoDB;

CREATE TABLE SORTIE(
   NUMSORT INT,
   dateSort DATETIME NOT NULL,
   NUMCLI INT NOT NULL,
   PRIMARY KEY(NUMSORT),
   FOREIGN KEY(NUMCLI) REFERENCES CLIENT(NUMCLI)
)ENGINE=InnoDB;

CREATE TABLE SAUNIER(
   NUMSAU INT,
   nomSau VARCHAR(30) NOT NULL,
   prenomSau VARCHAR(30) NOT NULL,
   villeSau VARCHAR(50) NOT NULL,
   PRIMARY KEY(NUMSAU)
)ENGINE=InnoDB;

CREATE TABLE Annee(
   numAnnee INT,
   PRIMARY KEY(numAnnee)
)ENGINE=InnoDB;

CREATE TABLE ENTREE(
   NUMENT INT,
   dateEnt DATETIME NOT NULL,
   qteEnt__t_ INT NOT NULL CHECK (qteEnt__t_ >0),
   NUMSAU INT NOT NULL,
   NUMPDT INT NOT NULL,
   PRIMARY KEY(NUMENT),
   FOREIGN KEY(NUMSAU) REFERENCES SAUNIER(NUMSAU),
   FOREIGN KEY(NUMPDT) REFERENCES PRODUIT(NUMPDT)
)ENGINE=InnoDB;

CREATE TABLE CONCERNER(
   NUMPDT INT,
   NUMSORT INT,
   qteSort_t_ INT NOT NULL,
   PRIMARY KEY(NUMPDT, NUMSORT),
   FOREIGN KEY(NUMPDT) REFERENCES PRODUIT(NUMPDT),
   FOREIGN KEY(NUMSORT) REFERENCES SORTIE(NUMSORT)
)ENGINE=InnoDB;

CREATE TABLE PRIX(
   NUMPDT INT,
   numAnnee INT,
   prixAchat INT,
   prixVente INT,
   PRIMARY KEY(NUMPDT, numAnnee),
   FOREIGN KEY(NUMPDT) REFERENCES PRODUIT(NUMPDT),
   FOREIGN KEY(numAnnee) REFERENCES Annee(numAnnee)
)ENGINE=InnoDB;
>>>>>>> 27f11b381f41a1ddff82b3391a781da52d95895e
